//Team Type
export const TEAMS_HAVE_ERROR = 'TEAMS_HAVE_ERROR';
export const TEAMS_ARE_LOADING = 'TEAMS_ARE_LOADING';
export const TEAMS_FETCH_DATA_SUCCESS = 'TEAMS_FETCH_DATA_SUCCESS';
//User Type
export const USER_HAVE_ERROR = 'USER_HAVE_ERROR';
export const USER_ARE_LOADING = 'USER_ARE_LOADING';
export const USER_FETCH_DATA_SUCCESS = 'USER_FETCH_DATA_SUCCESS';
